export const RevenueReports = 'Revenue Report';
export const Earning = 'Earning';
export const Transactions = 'Transactions';
export const Visitors = 'Visitors';
export const NewUpdate = 'New & Update';
export const ToDoList = 'To Do List';
export const Addtask = 'Add task';
export const RecentActivitys = 'Recent Activity';
export const BrowserStates = 'Browser States';
export const AddNewUser = 'Add New User';
export const AddNew = 'Add New';
export const AllUserss = 'All Users';
export const Account = 'Account';
export const Permission = 'Permission';
export const FirstName = 'First Name';
export const EmailAddress = 'Email Address';
export const Password = 'Password';
export const ConfirmPassword = 'Confirm Password';
export const ProductInformation = 'Product Information';
export const Submit = 'Submit';
export const OrderList = 'Order List';
export const OrderTracking = 'Order Tracking';
export const Cancel = 'Cancel';
export const CreateVendor = 'Create Vendor';
export const VendorList = 'Vendor List';
export const ProductsList = 'Products List';
export const AddNewProduct = 'Add New Product';
export const TranslationList = 'Translation List';
export const CurrencyRates = 'Currency Rates';
export const Taxess = 'Taxes';
export const MenuList = 'Menu List';
export const CreatedMenu = 'Created Menu';
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
