export const RevenueReports = 'Revenue Report';
export const Earning = 'Earning';
export const Transactions = 'Transactions';
export const Visitors = 'Visitors';
export const NewUpdate = 'New & Update';
export const ToDoList = 'To Do List';
export const Addtask = 'Add task';
export const RecentActivitys = 'Recent Activity';
export const BrowserStates = 'Browser States';
// export const RevenueReports = 'Revenue Report';
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report';
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report';
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report';
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report';
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report';
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
