export const RevenueReports = 'Revenue Report';
export const Earning = 'Earning';
export const Transactions = 'Transactions';
export const Visitors = 'Visitors';
export const NewUpdate = 'New & Update';
export const ToDoList = 'To Do List';
export const Addtask = 'Add task';
export const RecentActivitys = 'Recent Activity';
export const BrowserStates = 'Browser States';
export const AddNewUser = 'Add New User';
export const AddNew = 'Add New';
export const AllUserss = 'All Users';
export const Account = 'Account';
export const Permission = 'Permission';
// export const RevenueReports = 'Revenue Report';
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report';
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report';
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report';
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
